export const types = {
  ASK_TO_CONNECT: "ASK_TO_CONNECT",
  CONNECT_HOST: "CONNECT_HOST",
  NOT_REQUESTING_TO_JOIN_MEETING: "NOT_REQUESTING_TO_JOIN_MEETING",
  REQUEST_TO_JOIN_MEETING: "REQUEST_TO_JOIN_MEETING",
  GRANT_JOINING_MEETING: "GRANT_JOINING_MEETING",
  DENY_JOINING_MEETING: "DENY_JOINING_MEETING",
  INFORM_OTHERS_ABOUT_NEW_PARTICIPANT: "INFORM_OTHERS_ABOUT_NEW_PARTICIPANT",
  INFORM_NEW_PARTICIPANT_ABOUT_OTHERS: "INFORM_NEW_PARTICIPANT_ABOUT_OTHERS",
  INFORM_OTHERS_ABOUT_LEFT_PARTICIPANT: "INFORM_OTHERS_ABOUT_LEFT_PARTICIPANT",
  SDP_PROCESS: "SDP_PROCESS",
  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
};

export const labels = {
  NORMAL_PROCESS: "NORMAL_PROCESS",
  WEBRTC_PROCESS: "WEBRTC_PROCESS",
};
